### ISSUE TITLE
Input 0.01 ETH shows inifinity ETH 

### ISSUE THREAD

**Issue by pimato** [levelkdev/BC-DAPP#93]
currently:

<img width="331" alt="Screenshot 2020-04-03 at 15 07 04" src="https://user-images.githubusercontent.com/5337809/78363969-f866a780-75bc-11ea-9b3d-d0ad79987c5d.png">

Should:
<img width="418" alt="Screenshot 2020-04-02 at 19 48 21" src="https://user-images.githubusercontent.com/5337809/78281420-edf3d180-751a-11ea-93dc-92e39b72db48.png">

**Comment by tspoff** [comment]
Any value below the minimum investment shows infinity for price (because, estimateBuyValue returns 0)

![image](https://user-images.githubusercontent.com/5606917/78370162-4a470780-7594-11ea-912a-6efb9ad4e894.png)

Will add a special case for this - good find.

Also this will be fixed by making inputs BELOW minInvestment invalid
